services:
  solr:
    image: "solr:8.2.0"
    build: ./solr/
    container_name: solr
    restart: unless-stopped
    networks:
      - internal-network
    ports:
      - "8983:8983"
    volumes:
      - ./solr_dados/sei-protocolos:/dados/sei-protocolos/conteudo
      - ./solr_dados/sei-bases-conhecimento:/dados/sei-bases-conhecimento/conteudo
      - ./solr_dados/sei-publicacoes:/dados/sei-publicacoes/conteudo
  jodconverter:
    image: "jodconverter-tomcat:2.2.2"
    build: ./jod/
    container_name: jodconverter
    restart: unless-stopped
    networks:
      - internal-network
    ports:
      - "8080:8080"
  memcached:
    image: "memcached:1.6.36-alpine"
    container_name: memcached
    restart: unless-stopped
    env_file: env.ini
    networks:
      - internal-network
    ports:
      - "11211:11211"
  sei5-postgres:
    image: "sei5-postgres:1.0.0"
    build: ./postgres/
    container_name: sei5-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./docker/init-db/:/sql
    networks:
      - internal-network
  sei5-alpine:
    image: "sei5-alpine:1.0.0"
    build: ./sei5/
    container_name: sei5-alpine
    restart: unless-stopped
    env_file: env.ini
    depends_on:
      - sei5-postgres
    ports:
      - "8000:8000"
    volumes:
      - ./docker/src/sei:/opt/sei
      - ./docker/src/sip:/opt/sip
      - ./docker/src/infra:/opt/infra
      - ./docker/config/ConfiguracaoSEI.php:/opt/sei/config/ConfiguracaoSEI.php:ro
      - ./docker/config/ConfiguracaoSip.php:/opt/sip/config/ConfiguracaoSip.php:ro
    networks:
      - internal-network
    links:
      - memcached:memcached
      - solr:solr
      - jodconverter:jodconverter
    command: ["/bin/sh", "-c", "crond && httpd -DFOREGROUND"]
networks:
  internal-network:

